import type { Metadata } from "next";
import "./globals.css";
import { Ysabeau_Font } from "./components/Common/Fonts";
import React from "react";
import ProgressBar from "./progressBar";

export const metadata: Metadata = {
  title: "Live Meeting Harsh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${[Ysabeau_Font.variable, Ysabeau_Font.className].join(" ")} `}>
        {children}

        <React.Suspense fallback={"loding"}>
          <ProgressBar />
        </React.Suspense>
      </body>
    </html>
  );
}
